[phases.setup]
nixPkgs = ["php", "php83Extensions.pdo", "php83Extensions.pdo_pgsql", "php83Extensions.pgsql", "php83Extensions.mbstring", "php83Extensions.curl", "php83Extensions.openssl", "php83Extensions.session"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
